export const kowalski = {
  // Daily consumption
  categories: [
    {
      name: "Fruits",
      price: 0.101,
      utilityFactor: 1000,
      basicNeedAmount: 400,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "g",
    },
    {
      name: "Vegetables",
      price: 0.101,
      utilityFactor: 1000,
      basicNeedAmount: 500,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "g",
    },
    {
      name: "Meat",
      price: 6,
      utilityFactor: 1000,
      basicNeedAmount: 200,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "g",
    },
    {
      name: "Water",
      price: 0.009,
      utilityFactor: 1000,
      basicNeedAmount: 1750,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "ml",
    },
    {
      name: "Water (hygiene)",
      price: 0.009,
      utilityFactor: 1,
      basicNeedAmount: 50_000,
      diminishingFactor: 0.5,
      necessityLevel: 8,
      unit: "ml",
    },
    {
      name: "Oxygen",
      price: 0,
      utilityFactor: 1000,
      basicNeedAmount: 550_000,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "ml",
    },
    {
      name: "Oxygen (Sports)",
      price: 0,
      utilityFactor: 1000,
      basicNeedAmount: 1550_000,
      diminishingFactor: 0.5,
      necessityLevel: 10,
      unit: "ml",
    },
    {
      name: "Alcohol",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 250,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "ml",
    },
    {
      name: "Computer",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 2,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "h",
    },
    {
      name: "Sugar",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 3,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "g",
    },
    {
      name: "Tea",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 3,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "g",
    },
    {
      name: "Coffee",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 3,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "g",
    },
    {
      name: "Entertainment",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 1,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "h",
    },
    {
      name: "Culture",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.03,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "h",
    },
    {
      name: "Healthcare",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.00001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "fix-ups",
    },
    {
      name: "Tools",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "unit",
    },
    {
      name: "Personal care",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "l",
    },
    {
      name: "Household chemistry",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.00001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "unit",
    },
    {
      name: "Furniture",
      price: 0.101,
      utilityFactor: 1,
      basicNeedAmount: 0.0000001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "unit",
    },
    {
      name: "Clothes",
      price: 0.303,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "set",
    },
    {
      name: "Education",
      price: 0.4545,
      utilityFactor: 1,
      basicNeedAmount: 0.003,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "skills learned",
    },
    {
      name: "Pharmaceutics",
      price: 0.4545,
      utilityFactor: 1,
      basicNeedAmount: 0.002,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "packages",
    },
    {
      name: "Real estate",
      price: 2.6212000632425925,
      utilityFactor: 1,
      basicNeedAmount: 50,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "m2",
    },
    {
      name: "Brain Interface Chips",
      price: 101,
      utilityFactor: 1,
      basicNeedAmount: 0,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "unit",
    },
    {
      name: "Gene Therapy Services",
      price: 101,
      utilityFactor: 1,
      basicNeedAmount: 0,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "sessions",
    },
    {
      name: "Luxurious Clothes",
      price: 606,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 1,
      unit: "set",
    },
    {
      name: "Luxurious Real Estate",
      price: 757.5,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 1,
      unit: "m2",
    },
    {
      name: "Luxurious Entertainment",
      price: 757.5,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 1,
      unit: "session",
    },
    {
      name: "Relax",
      price: 0,
      utilityFactor: 1,
      basicNeedAmount: 0.0001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "session",
    },
    {
      name: "Air conditioning",
      price: 0,
      utilityFactor: 1,
      basicNeedAmount: 1,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "daily coverage",
    },
    {
      name: "Radiation protection",
      price: 0,
      utilityFactor: 1,
      basicNeedAmount: 1,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "daily coverage",
    },
    {
      name: "Law execution",
      price: 0,
      utilityFactor: 1,
      basicNeedAmount: 0.00001,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "session",
    },
    {
      name: "Propaganda",
      price: 0,
      utilityFactor: 1,
      basicNeedAmount: 1,
      diminishingFactor: 0.5,
      necessityLevel: 5,
      unit: "daily coverage",
    },
  ],
  // 5000PLN / 30 days
  budget: 166,
}
